#!/bin/sh

_log() {
	printf "$(tput setaf 5)-->$(tput setaf 2) %s$(tput setaf 7)\n" "$@"
}

_log_err() {
	printf "$(tput setaf 6)-->$(tput setaf 9) %s$(tput setaf 7)\n" "$@"
	exit 1
}

[ -z "$POLOCHON_TOKEN" ] && _log_err "Missing polochon token"
POLOCHON_URL="https://polochon.quimbo.fr"
TMPDIR=${TMPDIR:=/tmp}
CACHE_DELAY=$(( 60 * 5 ))

_usage() {
	_log_err "$(basename "$0") [movies|shows]"
}

_polochon_call() {
	method=$1
	resource=$2
	curl --silent --show-error \
		-X "$method" \
		-H "Content-Type: application/json" \
		-H "X-Auth-Token: $POLOCHON_TOKEN" \
		"$POLOCHON_URL/$resource"
}

_fetch() {
	uri=$1
	cache="$TMPDIR/polochon_$uri.json"

	last_update=$(stat -c "%Y" "$cache" 2>/dev/null || true)
	if [ -n "$last_update" ]; then
		now=$(date +%s)
		diff=$(( now - last_update ))
		[ "$diff" -ge "$CACHE_DELAY" ] && rm "$cache"
	fi

	[ -f "$cache" ] || _polochon_call "GET" "$uri" > "$cache"
	cat "$cache"
}

_fzf() {
	prompt=$1
	fzf --prompt="$prompt > "
}

_mpv() {
	title=$1
	uri=$2
	subtitles=$3

	sub_cmd=
	for lang in $subtitles; do
		sub_cmd="$sub_cmd --sub-file=$uri/subtitles/$lang/download?lang=$lang"
	done

	mpv \
		--http-header-fields="X-Auth-Token: $POLOCHON_TOKEN" \
		--title="$title" \
		$sub_cmd \
		"$uri/download?title=$title"
}

_movies() {
	title=$(_fetch "movies" | jq -r '.[] | .title?' | _fzf "Choose movie")
	[ -n "$title" ] || _log_err "No movie selected"

	movie=$(_fetch "movies" | jq -r "to_entries | .[] | select(.value.title == \"$title\")")
	imdb_id=$(echo "$movie" | jq -r .key)
	subtitles=$(echo "$movie" | jq -r '.value.subtitles? | .[] | select(.embedded == false) | .lang')

	_log "Streaming \"$title\" ($imdb_id)"

	movie_uri="$POLOCHON_URL/movies/$imdb_id"
	_mpv "$title" "$movie_uri" "$subtitles"
}

_shows() {
	title=$(_fetch "shows" | jq -r '.[] | .title?' | _fzf "Choose show")
	[ -n "$title" ] || _log_err "No show selected"

	show=$(_fetch "shows" | jq -r "to_entries | .[] | select(.value.title == \"$title\")")
	imdb_id=$(echo "$show" | jq -r .key)

	season=$(echo "$show" | jq -r ".value.seasons | keys | .[]" | _fzf "Choose season")
	[ -n "$season" ] || _log_err "No season selected"

	episode=$(echo "$show" | jq -r ".value.seasons.\"$season\" | keys | .[]" | _fzf "Choose episode")
	[ -n "$episode" ] || _log_err "No episode selected"

	subtitles=$(echo "$show" | jq -r ".value.seasons.\"$season\".\"$episode\".subtitles? | .[] | select(.embedded == false) | .lang")

	episode_title="$title S${season}E$episode"
	_log "Streaming $episode_title"

	episode_uri="$POLOCHON_URL/shows/$imdb_id/seasons/$season/episodes/$episode"
	_mpv "$episode_title" "$episode_uri" "$subtitles"
}

case "$1" in
	m|movie|movies) _movies ;;
	s|show|shows)   _shows  ;;
	*)              _usage  ;;
esac
